version: "3.2"

networks:
  default:
    external:
      name: common

services:
  politic_db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: politic123
      POSTGRES_USER: politic
      POSTGRES_DB: politic_game
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  politic_game:
    depends_on:
      - politic_db
    build: .
    restart: on-failure
    env_file:
      - .env
    privileged: true
    ports:
      - "8000:8000"
    command:
      - pipenv run migrate
      - pipenv run main
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'